org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Java/jdk-21.0.10

mod_id=antarchy
mod_name=Antarchy
mod_description=ANTS! ANTS! ANTS! ANTS!
mod_authors=CraisinLord
mod_group_id=com.craisinlord
mod_version=1.0.3
mod_license=All Rights Reserved

minecraft_version=1.20.1
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
parchment_version=2023.09.03-1.20.1

jei_version=15.20.0.104
geckolib_version=4.8.4
mixin_extras=0.5.0

sizeable_foliage_curseforge_id=1601832
sizeable_foliage_curseforge_file_id_forge=8468688

intapi_curseforge_id=817709
intapi_curseforge_file_id_forge=7921671

pehkui_curseforge_id=319596
pehkui_curseforge_file_id_forge=5393101
