package com.craisinlord.antarchy.forge.registry;

import com.craisinlord.antarchy.Antarchy;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.RegistryObject;

public final class AntarchyForgeSounds {
    private static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(Registries.SOUND_EVENT, Antarchy.MODID);

    public static final RegistryObject<SoundEvent> SQUIDZOOKA_FIRE = registerSoundEvent("squidzooka_fire");
    public static final RegistryObject<SoundEvent> SHRINK_RAY_SOUND = registerSoundEvent("shrink_ray");
    public static final RegistryObject<SoundEvent> GROWTH_RAY_SOUND = registerSoundEvent("growth_ray");
    public static final RegistryObject<SoundEvent> SIZE_RAY_CHARGE = registerSoundEvent("size_ray_charge");
    public static final RegistryObject<SoundEvent> ANT_AMBIENT = registerSoundEvent("ant_ambient");
    public static final RegistryObject<SoundEvent> ANT_IDLE = registerSoundEvent("ant_idle");
    public static final RegistryObject<SoundEvent> ANT_HURT = registerSoundEvent("ant_hurt");
    public static final RegistryObject<SoundEvent> ANT_BITE = registerSoundEvent("ant_bite");
    public static final RegistryObject<SoundEvent> ANT_GATHER = registerSoundEvent("ant_gather");
    public static final RegistryObject<SoundEvent> ANT_NEST = registerSoundEvent("ant_nest");
    public static final RegistryObject<SoundEvent> CLOUD_SHARK_BITE = registerSoundEvent("cloud_shark_bite");
    public static final RegistryObject<SoundEvent> CLOUD_SHARK_IDLE = registerSoundEvent("cloud_shark_idle");
    public static final RegistryObject<SoundEvent> CLOUD_SHARK_HURT = registerSoundEvent("cloud_shark_hurt");
    public static final RegistryObject<SoundEvent> CLOUD_SHARK_DEATH = registerSoundEvent("cloud_shark_death");
    public static final RegistryObject<SoundEvent> CLOUD_SHARK_FLY = registerSoundEvent("cloud_shark_fly");
    public static final RegistryObject<SoundEvent> CATERPILLAR_IDLE = registerSoundEvent("caterpillar_idle");
    public static final RegistryObject<SoundEvent> CATERPILLAR_HURT = registerSoundEvent("caterpillar_hurt");
    public static final RegistryObject<SoundEvent> CATERPILLAR_CRAWL = registerSoundEvent("caterpillar_crawl");
    public static final RegistryObject<SoundEvent> BUTTERFLY_HURT = registerSoundEvent("butterfly_hurt");
    public static final RegistryObject<SoundEvent> BRUTALFLY_IDLE = registerSoundEvent("brutalfly_idle");
    public static final RegistryObject<SoundEvent> BRUTALFLY_DEATH = registerSoundEvent("brutalfly_death");
    public static final RegistryObject<SoundEvent> ELYTHIA_FIREFLY_AMBIENT = registerSoundEvent("ambient.elythia.firefly");
    public static final RegistryObject<SoundEvent> ELYTHIA_OURANWOOD_FOREST_AMBIENT = registerSoundEvent("ambient.elythia.ouranwood_forest");
    public static final RegistryObject<SoundEvent> MISSILE_SQUID_AMBIENT = registerSoundEvent("missile_squid_ambient");
    public static final RegistryObject<SoundEvent> MISSILE_SQUID_HURT = registerSoundEvent("missile_squid_hurt");
    public static final RegistryObject<SoundEvent> MISSILE_SQUID_DEATH = registerSoundEvent("missile_squid_death");
    public static final RegistryObject<SoundEvent> MISSILE_SQUID_ATTACK = registerSoundEvent("missile_squid_attack");
    public static final RegistryObject<SoundEvent> KRAKEN_FLYING_LOOP = registerSoundEvent("kraken_flying_loop");
    public static final RegistryObject<SoundEvent> KRAKEN_FLYING_SIDEWAYS_LOOP = registerSoundEvent("kraken_flying_sideways_loop");
    public static final RegistryObject<SoundEvent> KRAKEN_ATTACK = registerSoundEvent("kraken_attack");
    public static final RegistryObject<SoundEvent> KRAKEN_SPIN = registerSoundEvent("kraken_spin");
    public static final RegistryObject<SoundEvent> KRAKEN_ROAR = registerSoundEvent("kraken_roar");
    public static final RegistryObject<SoundEvent> KRAKEN_SUMMON = registerSoundEvent("kraken_summon");
    public static final RegistryObject<SoundEvent> KRAKEN_HURT = registerSoundEvent("kraken_hurt");
    public static final RegistryObject<SoundEvent> KRAKEN_DEATH = registerSoundEvent("kraken_death");
    public static final RegistryObject<SoundEvent> BASILISK_IDLE_LOOP = registerSoundEvent("basilisk_idle_loop");
    public static final RegistryObject<SoundEvent> BASILISK_SLITHER_LOOP = registerSoundEvent("basilisk_slither_loop");
    public static final RegistryObject<SoundEvent> BASILISK_BITE = registerSoundEvent("basilisk_bite");
    public static final RegistryObject<SoundEvent> BASILISK_HISS = registerSoundEvent("basilisk_hiss");
    public static final RegistryObject<SoundEvent> BASILISK_HURT = registerSoundEvent("basilisk_hurt");
    public static final RegistryObject<SoundEvent> BASILISK_DEATH = registerSoundEvent("basilisk_death");
    public static final RegistryObject<SoundEvent> THORAXIS_NIGHTMARE_WASTES_AMBIENT = registerSoundEvent("thoraxis_nightmare_wastes_ambient");
    public static final RegistryObject<SoundEvent> THORAXIS_NIGHTMARE_WASTES_ADDITIONS = registerSoundEvent("thoraxis_nightmare_wastes_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_NIGHTMARE_WASTES_BIOME_ADDITIONS = registerSoundEvent("thoraxis_nightmare_wastes_biome_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_NIGHTMARE_WASTES_MOOD = registerSoundEvent("thoraxis_nightmare_wastes_mood");
    public static final RegistryObject<SoundEvent> THORAXIS_DREAM_DUNES_AMBIENT = registerSoundEvent("thoraxis_dream_dunes_ambient");
    public static final RegistryObject<SoundEvent> THORAXIS_DREAM_DUNES_ADDITIONS = registerSoundEvent("thoraxis_dream_dunes_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_DREAM_DUNES_BIOME_ADDITIONS = registerSoundEvent("thoraxis_dream_dunes_biome_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_DREAM_DUNES_MOOD = registerSoundEvent("thoraxis_dream_dunes_mood");
    public static final RegistryObject<SoundEvent> THORAXIS_LUCID_POOLS_AMBIENT = registerSoundEvent("thoraxis_lucid_pools_ambient");
    public static final RegistryObject<SoundEvent> THORAXIS_LUCID_POOLS_ADDITIONS = registerSoundEvent("thoraxis_lucid_pools_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_LUCID_POOLS_BIOME_ADDITIONS = registerSoundEvent("thoraxis_lucid_pools_biome_additions");
    public static final RegistryObject<SoundEvent> THORAXIS_LUCID_POOLS_MOOD = registerSoundEvent("thoraxis_lucid_pools_mood");
    public static final RegistryObject<SoundEvent> LUCID_AMBIENT = registerSoundEvent("lucid_ambient");
    public static final RegistryObject<SoundEvent> LUCID_FLYING = registerSoundEvent("lucid_flying");
    public static final RegistryObject<SoundEvent> LUCID_ATTACK = registerSoundEvent("lucid_attack");
    public static final RegistryObject<SoundEvent> LUCID_BOLT_SOUND = registerSoundEvent("lucid_bolt");
    public static final RegistryObject<SoundEvent> LUCID_HURT = registerSoundEvent("lucid_hurt");
    public static final RegistryObject<SoundEvent> LUCID_DEATH = registerSoundEvent("lucid_death");
    public static final RegistryObject<SoundEvent> REVERIE_IDLE = registerSoundEvent("reverie_idle");
    public static final RegistryObject<SoundEvent> REVERIE_HURT = registerSoundEvent("reverie_hurt");
    public static final RegistryObject<SoundEvent> REVERIE_WORRY = registerSoundEvent("reverie_worry");
    public static final RegistryObject<SoundEvent> REVERIE_SAVE = registerSoundEvent("reverie_save");
    public static final RegistryObject<SoundEvent> REVERIE_JOIN_PLAYER = registerSoundEvent("reverie_join_player");
    public static final RegistryObject<SoundEvent> REVERIE_ALERT = registerSoundEvent("reverie_alert");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_IDLE = registerSoundEvent("flying_squirrel_idle");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_BEG = registerSoundEvent("flying_squirrel_beg");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_NUT = registerSoundEvent("flying_squirrel_nut");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_GLIDE_LOOP = registerSoundEvent("flying_squirrel_glide_loop");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_HURT = registerSoundEvent("flying_squirrel_hurt");
    public static final RegistryObject<SoundEvent> FLYING_SQUIRREL_DEATH = registerSoundEvent("flying_squirrel_death");
    public static final RegistryObject<SoundEvent> NIGHTMARE_IDLE = registerSoundEvent("nightmare_idle");
    public static final RegistryObject<SoundEvent> NIGHTMARE_HURT = registerSoundEvent("nightmare_hurt");
    public static final RegistryObject<SoundEvent> NIGHTMARE_ROAR = registerSoundEvent("nightmare_roar");
    public static final RegistryObject<SoundEvent> NIGHTMARE_DEATH = registerSoundEvent("nightmare_death");
    public static final RegistryObject<SoundEvent> NIGHTMARE_BITE = registerSoundEvent("nightmare_bite");
    public static final RegistryObject<SoundEvent> NIGHTMARE_FLAP = registerSoundEvent("nightmare_flap");
    public static final RegistryObject<SoundEvent> TRIFFID_ATTACK = registerSoundEvent("triffid_attack");
    public static final RegistryObject<SoundEvent> TRIFFID_GRAB = registerSoundEvent("triffid_grab");
    public static final RegistryObject<SoundEvent> TRIFFID_HURT = registerSoundEvent("triffid_hurt");
    public static final RegistryObject<SoundEvent> TRIFFID_DEATH = registerSoundEvent("triffid_death");
    public static final RegistryObject<SoundEvent> TRIFFID_HISS = registerSoundEvent("triffid_hiss");
    public static final RegistryObject<SoundEvent> TRIFFID_GROWL = registerSoundEvent("triffid_growl");
    public static final RegistryObject<SoundEvent> MANTIS_AMBIENT = registerSoundEvent("mantis_ambient");
    public static final RegistryObject<SoundEvent> MANTIS_HURT = registerSoundEvent("mantis_hurt");
    public static final RegistryObject<SoundEvent> MANTIS_ATTACK = registerSoundEvent("mantis_attack");
    public static final RegistryObject<SoundEvent> MANTIS_FLY_LOOP = registerSoundEvent("mantis_fly_loop");
    public static final RegistryObject<SoundEvent> GRAVITY_GUN_PICKUP = registerSoundEvent("gravity_gun_pickup");
    public static final RegistryObject<SoundEvent> GRAVITY_GUN_DROP = registerSoundEvent("gravity_gun_drop");
    public static final RegistryObject<SoundEvent> GRAVITY_GUN_HOLD_LOOP = registerSoundEvent("gravity_gun_hold_loop");
    public static final RegistryObject<SoundEvent> GRAVITY_GUN_LAUNCH = registerSoundEvent("gravity_gun_launch");
    public static final RegistryObject<SoundEvent> GRAVITY_GUN_DRYFIRE = registerSoundEvent("gravity_gun_dryfire");
    public static final RegistryObject<SoundEvent> BED_BUG_AMBIENT = registerSoundEvent("bed_bug_ambient");
    public static final RegistryObject<SoundEvent> BED_BUG_HURT = registerSoundEvent("bed_bug_hurt");
    public static final RegistryObject<SoundEvent> BED_BUG_ATTACK = registerSoundEvent("bed_bug_attack");
    public static final RegistryObject<SoundEvent> WASP_IDLE = registerSoundEvent("wasp_idle");
    public static final RegistryObject<SoundEvent> WASP_HURT = registerSoundEvent("wasp_hurt");
    public static final RegistryObject<SoundEvent> WASP_ATTACK = registerSoundEvent("wasp_attack");
    public static final RegistryObject<SoundEvent> WASP_DEATH = registerSoundEvent("wasp_death");
    public static final RegistryObject<SoundEvent> SCORPION_AMBIENT = registerSoundEvent("scorpion_ambient");
    public static final RegistryObject<SoundEvent> SCORPION_HURT = registerSoundEvent("scorpion_hurt");
    public static final RegistryObject<SoundEvent> SCORPION_ATTACK = registerSoundEvent("scorpion_attack");
    public static final RegistryObject<SoundEvent> EMPEROR_SCORPION_AMBIENT = registerSoundEvent("emperor_scorpion_ambient");
    public static final RegistryObject<SoundEvent> EMPEROR_SCORPION_HURT = registerSoundEvent("emperor_scorpion_hurt");
    public static final RegistryObject<SoundEvent> EMPEROR_SCORPION_ATTACK = registerSoundEvent("emperor_scorpion_attack");
    public static final RegistryObject<SoundEvent> EMPEROR_SCORPION_ROAR = registerSoundEvent("emperor_scorpion_roar");
    public static final RegistryObject<SoundEvent> MOLEWORM_AMBIENT = registerSoundEvent("moleworm_ambient");
    public static final RegistryObject<SoundEvent> MOLEWORM_HURT = registerSoundEvent("moleworm_hurt");
    public static final RegistryObject<SoundEvent> MOLEWORM_ATTACK = registerSoundEvent("moleworm_attack");
    public static final RegistryObject<SoundEvent> MOLEWORM_DIG = registerSoundEvent("moleworm_dig");
    public static final RegistryObject<SoundEvent> MOLEVORE_AMBIENT = registerSoundEvent("molevore_ambient");
    public static final RegistryObject<SoundEvent> MOLEVORE_HURT = registerSoundEvent("molevore_hurt");
    public static final RegistryObject<SoundEvent> MOLEVORE_ATTACK = registerSoundEvent("molevore_attack");
    public static final RegistryObject<SoundEvent> MOLEVORE_DIG = registerSoundEvent("molevore_dig");
    public static final RegistryObject<SoundEvent> BOMBER_WALK = registerSoundEvent("bomber_walk");
    public static final RegistryObject<SoundEvent> BOMBER_KNOCK = registerSoundEvent("bomber_knock");
    public static final RegistryObject<SoundEvent> BOMBER_EXPLODE = registerSoundEvent("bomber_explode");
    public static final RegistryObject<SoundEvent> TORETERROR_IDLE = registerSoundEvent("toreterror_idle");
    public static final RegistryObject<SoundEvent> TORETERROR_HURT = registerSoundEvent("toreterror_hurt");
    public static final RegistryObject<SoundEvent> TORETERROR_DEATH = registerSoundEvent("toreterror_death");
    public static final RegistryObject<SoundEvent> TORETERROR_BOMBER_FIRE = registerSoundEvent("toreterror_bomber_fire");
    public static final RegistryObject<SoundEvent> TORETERROR_SPIN = registerSoundEvent("toreterror_spin");
    public static final RegistryObject<SoundEvent> TORETERROR_RICOCHET = registerSoundEvent("toreterror_ricochet");
    public static final RegistryObject<SoundEvent> WATER_CANNON_FIRE = registerSoundEvent("water_cannon_fire");
    public static final RegistryObject<SoundEvent> TORETERROR_JUMP_UP = registerSoundEvent("toreterror_jump_up");
    public static final RegistryObject<SoundEvent> TORETERROR_JUMP_LAND = registerSoundEvent("toreterror_jump_land");
    public static final RegistryObject<SoundEvent> STINKY_FLY = registerSoundEvent("stinky_fly");
    public static final RegistryObject<SoundEvent> STINK_BUG_FART = registerSoundEvent("stink_bug_fart");
    public static final RegistryObject<SoundEvent> STINK_BUG_IDLE = registerSoundEvent("stink_bug_idle");
    public static final RegistryObject<SoundEvent> CAVARYN_HEARTBEAT = registerSoundEvent("cavaryn_heartbeat");
    public static final RegistryObject<SoundEvent> ROLLY_POLLY_IDLE = registerSoundEvent("rolly_polly_idle");
    public static final RegistryObject<SoundEvent> ROLLY_POLLY_WHEEL_MODE = registerSoundEvent("rolly_polly_wheel_mode");
    public static final RegistryObject<SoundEvent> ROLLY_POLLY_NORMAL_MODE = registerSoundEvent("rolly_polly_normal_mode");
    public static final RegistryObject<SoundEvent> ROLLY_POLLY_ROLL = registerSoundEvent("rolly_polly_roll");
    public static final RegistryObject<SoundEvent> CREEPING_HORROR_GROWL = registerSoundEvent("creeping_horror_growl");
    public static final RegistryObject<SoundEvent> CREEPING_HORROR_HURT = registerSoundEvent("creeping_horror_hurt");
    public static final RegistryObject<SoundEvent> CREEPING_HORROR_BITE = registerSoundEvent("creeping_horror_bite");
    public static final RegistryObject<SoundEvent> LURKING_TERROR_SNARL = registerSoundEvent("lurking_terror_snarl");
    public static final RegistryObject<SoundEvent> LURKING_TERROR_HURT = registerSoundEvent("lurking_terror_hurt");
    public static final RegistryObject<SoundEvent> LURKING_TERROR_BITE = registerSoundEvent("lurking_terror_bite");
    public static final RegistryObject<SoundEvent> LURKING_TERROR_FLY_LOOP = registerSoundEvent("lurking_terror_fly_loop");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_IDLE = registerSoundEvent("hercules_beetle_idle");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_HURT = registerSoundEvent("hercules_beetle_hurt");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_ATTACK = registerSoundEvent("hercules_beetle_attack");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_CRY = registerSoundEvent("hercules_beetle_cry");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_CHARGE_START = registerSoundEvent("hercules_beetle_charge_start");
    public static final RegistryObject<SoundEvent> HERCULES_BEETLE_KNOCKED_DOWN = registerSoundEvent("hercules_beetle_knocked_down");
    public static final RegistryObject<SoundEvent> JUMPY_BUG_IDLE = registerSoundEvent("jumpy_bug_idle");
    public static final RegistryObject<SoundEvent> SPIT_BUG_IDLE = registerSoundEvent("spit_bug_idle");
    public static final RegistryObject<SoundEvent> JUMPY_BUG_HURT = registerSoundEvent("jumpy_bug_hurt");
    public static final RegistryObject<SoundEvent> JUMPY_BUG_JUMP = registerSoundEvent("jumpy_bug_jump");
    public static final RegistryObject<SoundEvent> SPIT_BUG_HURT = registerSoundEvent("spit_bug_hurt");
    public static final RegistryObject<SoundEvent> SPIT_BUG_SPIT = registerSoundEvent("spit_bug_spit");
    public static final RegistryObject<SoundEvent> BRUTALFLY_SPIT = registerSoundEvent("brutalfly_spit");
    public static final RegistryObject<SoundEvent> JERRY_YOUNG_IDLE = registerSoundEvent("jerry_young_idle");
    public static final RegistryObject<SoundEvent> JERRY_YOUNG_HURT = registerSoundEvent("jerry_young_hurt");
    public static final RegistryObject<SoundEvent> JERRY_YOUNG_DEATH = registerSoundEvent("jerry_young_death");
    public static final RegistryObject<SoundEvent> JERRY_YOUNG_ATTACK = registerSoundEvent("jerry_young_attack");
    public static final RegistryObject<SoundEvent> JERRY_ADULT_IDLE = registerSoundEvent("jerry_adult_idle");
    public static final RegistryObject<SoundEvent> JERRY_ADULT_HURT = registerSoundEvent("jerry_adult_hurt");
    public static final RegistryObject<SoundEvent> JERRY_ADULT_DEATH = registerSoundEvent("jerry_adult_death");
    public static final RegistryObject<SoundEvent> JERRY_ADULT_ATTACK = registerSoundEvent("jerry_adult_attack");
    public static final RegistryObject<SoundEvent> DUCT_TAPE_USE = registerSoundEvent("duct_tape_use");
    public static final RegistryObject<SoundEvent> POTENT_NYXITE_HYPNOTIC_GAS = registerSoundEvent("potent_nyxite_hypnotic_gas");
    public static final RegistryObject<SoundEvent> POTENT_NYXITE_GEYSER_ERUPTION_START = registerSoundEvent("potent_nyxite_geyser_eruption_start");
    public static final RegistryObject<SoundEvent> POTENT_NYXITE_GEYSER_ERUPTION_ACTIVE = registerSoundEvent("potent_nyxite_geyser_eruption_active");
    public static final RegistryObject<SoundEvent> POTENT_NYXITE_GEYSER_CONTINUOUS_START = registerSoundEvent("potent_nyxite_geyser_continuous_start");
    public static final RegistryObject<SoundEvent> POTENT_NYXITE_GEYSER_CONTINUOUS_ACTIVE = registerSoundEvent("potent_nyxite_geyser_continuous_active");

    private AntarchyForgeSounds() {}

    public static void register(IEventBus modEventBus) {
        SOUND_EVENTS.register(modEventBus);
    }

    private static RegistryObject<SoundEvent> registerSoundEvent(String path) {
        return SOUND_EVENTS.register(path,
                () -> SoundEvent.createVariableRangeEvent(new ResourceLocation(Antarchy.MODID, path)));
    }
}
