plugins {
    id 'java-library'
}

base {
    archivesName = "${mod_id}-common-1.21.1"
}

tasks.named('compileJava').configure {
    enabled = false
}

tasks.named('jar').configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.allJava
    from sourceSets.main.resources
}

dependencies {
    compileOnly("curse.maven:intapi-${intapi_curseforge_id}:${intapi_curseforge_file_id_neoforge}")
    compileOnly "maven.modrinth:infinite-dimensions:${project.infinite_dimensions_version}"
    compileOnly "maven.modrinth:gravity-changer-unofficial-port:${project.gravity_api_version}"
    compileOnly "maven.modrinth:sable:${project.sable_version}"
    compileOnly "maven.modrinth:sizeable-foliage:${project.sizeable_foliage_version}"
    compileOnly("software.bernie.geckolib:geckolib-neoforge-1.21.1:${geckolib_version}")
    compileOnly("mezz.jei:jei-1.21.1-common-api:${jei_version}")
}
